filter:
    paths:
        - src/*
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    external_code_coverage:
        timeout: 600

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
