dist: xenial
os: linux
language: php


# avoid double Travis build when the PR is created on upstream
if: |
    type = pull_request OR \
    branch = master

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.2
          env: CS_FIXER=run COVERAGE=run

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --no-progress --no-interaction -o --no-suggest
    - php vendor/bin/simple-phpunit install

before_script:
    - if [ "$COVERAGE" = "run" ]; then PHPUNIT_FLAGS="--coverage-clover coverage.clover"; fi;

script:
    - php vendor/bin/simple-phpunit -v $PHPUNIT_FLAGS
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/phpstan analyse ; fi;


after_success:
    - |
        if [ "$COVERAGE" = "run" ]; then
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        fi
