language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.0
          env: PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml" CS_FIXER=run

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - travis_retry composer self-update

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - php vendor/bin/simple-phpunit -v $PHPUNIT_FLAGS
    - if [ "$CS_FIXER" = "run" ]; then php vendor/bin/php-cs-fixer fix --verbose --dry-run ; fi;

after_script:
    - if [[ "$PHPUNIT_FLAGS" != "" ]]; then php vendor/bin/coveralls -v; fi;
